### PR TITLE
Minor fix on lines 30 & 45

### PR DESCRIPTION
**Pull request by kant**
Signed-off-by: Darío Hereñú magallania@gmail.com

### CODE REVIEW

**Comment by kuanf** [comment]
@gyliu513 @morvencao  why this pr does not trigger the prow jobs?

**Comment by gyliu513** [comment]
@kant is not a member of IBM Org, so need a member to help trigger the prow via `/ok-to-test`.

**Comment by gyliu513** [comment]
@kant can you help update your commit message by adding the following:

```
Signed-off-by: <Your Name> <Your Email Address>
```

**Comment by kant** [comment]
@gyliu513 Original PR with the instructions: Done!

**Pull request merged**
